ivana-chess:
  server:
    # Server bind address
    bind-address: ${IVANA_CHESS_BIND_ADDRESS:0.0.0.0}
    # Server port
    port: ${IVANA_CHESS_PORT:8080}
  webapp:
    # Base URL to web application.
    base-url: ${IVANA_CHESS_WEBAPP_URL:http://localhost:4200}
    # Path to game page.
    game-path: /game

server:
  address: ${ivana-chess.server.bind-address}
  port: ${ivana-chess.server.port}

spring:
  jackson:
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    dev.gleroy.ivanachess: ${IVANA_CHESS_LOG_LEVEL:info}
