ivana-chess:
  server:
    # Server bind address
    bind-address: ${IVANA_CHESS_BIND_ADDRESS:0.0.0.0}
    # Server port
    port: ${IVANA_CHESS_PORT:8080}
    # Coma-separated list of allowed origins
    allowed-origins: ${IVANA_ALLOWED_ORIGINS}

server:
  address: ${ivana-chess.server.bind-address}
  port: ${ivana-chess.server.port}

spring:
  jackson:
    default-property-inclusion: non_null
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    dev.gleroy.ivanachess: ${IVANA_CHESS_LOG_LEVEL:info}
