ivana-chess:
  server:
    # Server bind address
    bind-address: ${IVANA_CHESS_BIND_ADDRESS:0.0.0.0}
    # Server port
    port: ${IVANA_CHESS_PORT:8080}
    # Context path
    context-path: ${IVANA_CHESS_CONTEXT_PATH:/}
    # Coma-separated list of allowed origins
    allowed-origins: ${IVANA_CHESS_ALLOWED_ORIGINS}
  db:
    # JDBC URL of database
    url: ${IVANA_CHESS_DB_URL:jdbc:postgresql://127.0.0.1:5432/ivana_chess_api?currentSchema=public}
    # Username used to connect to database
    username: ${IVANA_CHESS_DB_USERNAME:ivana_chess_api}
    # Password used to connect to database
    password: ${IVANA_CHESS_DB_PASSWORD:ivana_chess_api}
  auth:
    # Secret used to generate JWT
    secret: ${IVANA_CHESS_AUTH_SECRET:changeit}
    # Number of seconds for which the JWT is valid
    validity: ${IVANA_CHESS_AUTH_EXPIRATION:604800}
    header:
      # HTTP header name which contains JWT
      name: ${IVANA_CHESS_AUTH_HEADER_NAME:Authorization}
      # Prefix of HTTP header value which prefixes JWT
      value-prefix: ${IVANA_CHESS_AUTH_HEADER_VALUE_PREFIX:Bearer }
    cookie:
      # Name of cookie used to send JWT
      name: ${IVANA_CHESS_AUTH_COOKIE_NAME:_ivana_chess_session}
      # Domain of cookie
      domain: ${IVANA_CHESS_AUTH_COOKIE_DOMAIN:localhost}
      # If cookie secure attribute is enabled
      secure: ${IVANA_CHESS_AUTH_COOKIE_SECURE:false}
      # If cookie http only attribute is enabled
      http-only: ${IVANA_CHESS_AUTH_COOKIE_HTTP_ONLY:true}

server:
  address: ${ivana-chess.server.bind-address}
  port: ${ivana-chess.server.port}
  servlet:
    context-path: ${ivana-chess.server.context-path}

spring:
  datasource:
    url: ${ivana-chess.db.url}
    username: ${ivana-chess.db.username}
    password: ${ivana-chess.db.password}
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: classpath:/db/changelog.yml
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    dev.gleroy.ivanachess: ${IVANA_CHESS_LOG_LEVEL:info}
