version: '3.6'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: ivana_chess_api
      POSTGRES_PASSWORD: ivana_chess_api
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  broker:
    image: gleroy/rabbitmq-stomp:3.7
    ports:
      - 61613:61613
