version: '3.6'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: ivanachessapi
      POSTGRES_PASSWORD: ivanachessapi
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
