version: '3.6'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: ivana_chess_api
      POSTGRES_PASSWORD: ivana_chess_api
    ports:
      - 5432:5432
  broker:
    image: gleroy/rabbitmq-stomp:3.7-1
    ports:
      - 5672:5672
      - 61613:61613
