version: '3.6'

services:
  db:
    build: ./docker/db
    environment:
      POSTGRES_USER: ivana_chess_api
      POSTGRES_PASSWORD: ivana_chess_api
    ports:
      - 5432:5432
  broker:
    image: gleroy/rabbitmq-stomp:3.7-1
    ports:
      - 5671:5671
      - 5672:5672
      - 61613:61613
      - 61614:61614
    volumes:
      - ./docker/broker/ssl:/etc/ssl/rabbitmq
      - ./docker/broker/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
