name: CI

on:
  push:
    branches:
      - '*'

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    container:
      image: gradle:6.8-jdk11
    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: ivanachessapi
          POSTGRES_PASSWORD: ivanachessapi
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: gradle assemble -x ivana-chess-webapp:assemble
      - name: Test
        run: gradle check -x ivana-chess-webapp:check -Pivana-chess-api.db.host=db -Pivana-chess-api.db.test-schema=public -Pci=true

  webapp:
    name: Webapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.4
      - name: Install dependencies
        run: npm install
        working-directory: ./webapp
      - name: Lint
        run: npm run lint
        working-directory: ./webapp
      - name: Build
        run: npm run build -- --prod
        working-directory: ./webapp
