on:
  push:
    tags:
      - '*'

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: dawidd6/action-get-tag@v1
        id: tag
      - name: Build
        run: ./gradlew assemble
      - name: Build Docker image
        run: ./gradlew buildDockerImage
      - name: Push Docker image
        run: ./gradlew pushDockerImage
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload API tarball
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./api/build/distributions/ivana-chess-api-${{ steps.tag.outputs.tag }}.tar.gz
          asset_name: ivana-chess-api-${{ steps.tag.outputs.tag }}.tar.gz
          asset_content_type: application/tar+gzip
      - name: Upload API fatjar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./api/build/libs/ivana-chess-api-${{ steps.tag.outputs.tag }}-fatjar.jar
          asset_name: ivana-chess-api-${{ steps.tag.outputs.tag }}.jar
          asset_content_type: application/java-archive
      - name: Upload Matchmaker tarball
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./matchmaker/build/distributions/ivana-chess-matchmaker-${{ steps.tag.outputs.tag }}.tar.gz
          asset_name: ivana-chess-matchmaker-${{ steps.tag.outputs.tag }}.tar.gz
          asset_content_type: application/tar+gzip
      - name: Upload Matchmaker fatjar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./matchmaker/build/libs/ivana-chess-matchmaker-${{ steps.tag.outputs.tag }}-fatjar.jar
          asset_name: ivana-chess-matchmaker-${{ steps.tag.outputs.tag }}.jar
          asset_content_type: application/java-archive
      - name: Upload webapp tarball
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./webapp/build/ivana-chess-webapp-${{ steps.tag.outputs.tag }}.tar.gz
          asset_name: ivana-chess-webapp-${{ steps.tag.outputs.tag }}.tar.gz
          asset_content_type: application/tar+gzip
